### ISSUE TITLE
UnexpectedTokenException on CREATE INDEX with ALGORITHM=INPLACE used 

### ISSUE THREAD

**Issue by janedbal** [SQLFTW/sqlftw#9]
Trying to parse `CREATE INDEX my_index ON my_table (my_column) ALGORITHM=INPLACE LOCK=NONE;` by

```php
$platform = Platform::get(Platform::MYSQL, '8.0');
$settings = new PlatformSettings($platform);
$parser = new Parser($settings);
$commands = $parser->parse($query);
```

Callstack:
```
Uncaught SqlFtw\Parser\UnexpectedTokenException: Expected token KEYWORD, but token SYMBOL|OPERATOR with value "=" (1) found instead at position 9 in:
"…CREATEINDEXMY_INDEXONMY_TABLE(MY_COLUMN)ALGORITHM»=«INPLACELOCK=NONE…" in /app/vendor/sqlftw/sqlftw/sources/Parser/TokenList.php:165
#0 /app/vendor/sqlftw/sqlftw/sources/Parser/TokenList.php(559): SqlFtw\Parser\TokenList->expect(256)
#1 /app/vendor/sqlftw/sqlftw/sources/Parser/TokenList.php(602): SqlFtw\Parser\TokenList->expectAnyKeyword('...', '...', '...', '...')
#2 /app/vendor/sqlftw/sqlftw/sources/Parser/Ddl/IndexCommandsParser.php(69): SqlFtw\Parser\TokenList->expectKeywordEnum('...')
#3 /app/vendor/sqlftw/sqlftw/sources/Parser/Parser.php(258): SqlFtw\Parser\Ddl\IndexCommandsParser->parseCreateIndex(Object(SqlFtw\Parser\TokenList))
#4 /app/vendor/sqlftw/sqlftw/sources/Parser/Parser.php(66): SqlFtw\Parser\Parser->parseTokenList(Object(SqlFtw\Parser\TokenList))
```

**Comment by paranoiq** [comment]
hi. it is always a good idea to state the version you are using : ]

i have tagged a new version and written a little about how it is tested: https://github.com/SQLFTW/sqlftw/releases/tag/v0.1.3
